load("/Users/qiranjia19961112/Desktop/LUCIDus-3.0/data/sim_data.rda")
library(glmnet)
library(glasso)
library(nnet)
library(networkD3)
library(mclust)
library(boot)
library(progress)



source("~/Desktop/LUCIDus-3.0/R/boot_lucid.R")
source("~/Desktop/LUCIDus-3.0/R/em.R")
source("~/Desktop/LUCIDus-3.0/R/parallel_mstep.R")
source("~/Desktop/LUCIDus-3.0/R/early_estep.R")
source("~/Desktop/LUCIDus-3.0/R/early_mstep.R")
source("~/Desktop/LUCIDus-3.0/R/lucid.R")
source("~/Desktop/LUCIDus-3.0/R/missing.R")
source("~/Desktop/LUCIDus-3.0/R/parallel_estep.R")
source("~/Desktop/LUCIDus-3.0/R/parallel_mstep.R")
source("~/Desktop/LUCIDus-3.0/R/plot_lucid.R")
source("~/Desktop/LUCIDus-3.0/R/pred_lucid.R")
source("~/Desktop/LUCIDus-3.0/R/predict_lucid_all.R")
source("~/Desktop/LUCIDus-3.0/R/summary.R")
source("~/Desktop/LUCIDus-3.0/R/tune_lucid.R")
source("~/Desktop/LUCIDus-3.0/R/utility.R")
source("~/Desktop/LUCIDus-3.0/R/EM_all.R")
source("~/Desktop/LUCIDus-3.0/R/summary_auxi_fxn_serial.R")